[Release-2020-02] chore: update webhook docs
livingdocsIO/livingdocs pull request #367
Opened 2021-03-02 09:01 UTC by mokimo

Add new webhooks according to https://github.com/livingdocsIO/livingdocs-server/pull/3359

2021-03-08 12:26 UTC, benib commented on reference-docs/server-configuration/webhooks.md
> +- added `document.published` and `document.publish` added in [`release-2020-05`](https://github.com/livingdocsIO/livingdocs-release-notes/blob/master/releases/release-2020-05.md)
```suggestion
- The feature and the two events `document.published` and `document.publish` were added in [`release-2020-05`](https://github.com/livingdocsIO/livingdocs-release-notes/blob/master/releases/release-2020-05.md)
```

2021-03-08 12:29 UTC, benib requested changes

2021-03-08 12:29 UTC, benib commented on reference-docs/server-configuration/webhooks.md
> +- all other events added in `release-2021-03`
Do we have a list somewhere with all these events? Would make sense to link it here, or list them directly.

2021-03-08 16:53 UTC, peyerluk commented
Release-2020-02? :)

2021-03-09 18:45 UTC, mokimo commented on reference-docs/server-configuration/webhooks.md
> +- all other events added in `release-2021-03`
Thanks for the two suggestions. Committed your suggested change & added a list with the webhooks that were added in the `release-2021-03`

2021-03-12 17:30 UTC, merged

2021-04-07 00:23 UTC, livingdocs-automation commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/livingdocsIO/documentation/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: