Telemetry
livingdocsIO/livingdocs pull request #381
Opened 2021-03-25 20:07 UTC by ajwild

Is it ok to dump the telemetry schema in there, or should I simplify it to the way it would be added in the server config with some additional comments?

2021-03-29 09:07 UTC, DaRaFF requested changes
Thanks for adding the doc! Please add an intro section to describe why one would need that feature :-)

2021-03-29 09:07 UTC, DaRaFF commented on content/operations/telemetry.md
> +```js
always mention what kind of config it is, e.g. server config, project config, editor config

2021-03-29 09:07 UTC, DaRaFF commented on content/operations/telemetry.md
> +
Please add some introduction. For what is this feature, why and how can it be used, what is the scope and so on.

2021-03-29 09:07 UTC, DaRaFF commented on content/operations/telemetry.md
> +Most of the options available are forwarded to the various `@opentelemetry` libraries used by the server, and it's not necessary to configure them. Please see the documentation for each npm package m
If you would provide a link to the different docs it would be easier for the reader of this doc.

2021-03-29 09:09 UTC, DaRaFF commented
> Is it ok to dump the telemetry schema in there, or should I simplify it to the way it would be added in the server config and then add some additional comments?

I think a valid example does with additional comments does help more.

2021-03-29 09:10 UTC, DaRaFF commented on content/operations/telemetry.md
> +
Adding one example of how to get some info and what to do with it would also be nice.

2021-03-29 10:47 UTC, marcbachmann commented on content/operations/telemetry.md
> +menu: operations
Could you add a `description: ` here to improve the text search.
`description: Use opentelemetry to get metrics and traces out of the Livingdocs Server instance.`

2021-04-03 10:18 UTC, ajwild commented on devops/telemetry.md
> +---
@marcbachmann, there seem to have been a few changes to the next branch recently. Has it switched back to GitBook? Should this be opened against master instead? Do I need to replace this with `# Telemetry`? I put the images directly in the devops folder now as there were some existing ones.

2021-04-06 06:44 UTC, DaRaFF commented on devops/telemetry.md
> +The telemetry stack will assit you in debugging your Livingdocs server instance. It enables you to build dashboards to provide an overview of the server and its surrounding environment, or to dive de
```suggestion
The telemetry stack will assist you in debugging your Livingdocs server instance. It enables you to build dashboards to provide an overview of the server and its surrounding environment, or to dive deeper into the metrics, logs and traces produced by the server.
```

2021-04-06 07:12 UTC, DaRaFF commented on devops/telemetry.md
> +At this point you should be able to create new dashboards full of beautiful graphs, guages and tables, as well as exploring/querying Jaeger, Loki, and Prometheus data and setting up alerts for outage
```suggestion
At this point you should be able to create new dashboards full of beautiful graphs, gauges and tables, as well as exploring/querying Jaeger, Loki, and Prometheus data and setting up alerts for outages, usage spikes, or errors.
```

2021-04-06 07:15 UTC, DaRaFF commented on devops/telemetry.md
> +{{< img src="grafana-logs-and-traces.png" alt="Grafana UI showing Loki logs and a linked Jaeger trace" >}}
is this a valid Markdown format? Usually the format looks more like that: `![Image of Yaktocat](https://octodex.github.com/images/yaktocat.png)`

2021-04-06 07:18 UTC, DaRaFF approved these changes

2021-04-06 08:50 UTC, ajwild commented on devops/telemetry.md
> +{{< img src="grafana-logs-and-traces.png" alt="Grafana UI showing Loki logs and a linked Jaeger trace" >}}
This is the Hugo syntax that was introduced. I'm waiting to see what the plan is, but it looks like we're going back to markdown with GitBook...

2021-04-06 09:37 UTC, ajwild commented
Rebased and now the Hugo things are working again :+1:

2021-04-06 10:19 UTC, marcbachmann commented on devops/telemetry.md
> +{{< img src="grafana-logs-and-traces.png" alt="Grafana UI showing Loki logs and a linked Jaeger trace" >}}
If we use the hugo shortcode syntax, it will report missing images automatically.
The normal markdown based tag will only go through the regular markdown processing and won't check the references and it will only work if we move the file to `devops/telemetry/index.md`.
So this is one small disadvantage of the setup, but I'd say it's acceptable with all the benefits it brings.

2021-04-06 10:20 UTC, marcbachmann approved these changes

2021-04-06 11:34 UTC, merged